### ISSUE TITLE
Unable to load extension: No module named html.entities

### ISSUE THREAD

**Issue by dataexcess** [madskjeldgaard/Cookiejuce#3]
I created a folder. I cd'ed into it. 
I ran 'pip install cookiecutter'. 
then I ran 'cookiecutter https://github.com/madskjeldgaard/Cookiejuce'

➜ cookiecutter https://github.com/madskjeldgaard/Cookiejuce 
You've downloaded /Users/Dataexcess/.cookiecutters/Cookiejuce before. Is it okay to delete and re-download it? [yes]: yes
Unable to load extension: No module named html.entities

What am I doing wrong?
Thnx

**Comment by madskjeldgaard** [comment]
Hi ! Thanks for the report. That is strange - I haven’t encountered this before. It seems like a problem with your python installation. Try running python —version and post the result here, please.On 12 Feb 2024, at 10.58, dataexcess ***@***.***> wrote:﻿
I created a folder. I cd'ed into it.
I ran 'pip install cookiecutter'.
then I ran 'cookiecutter https://github.com/madskjeldgaard/Cookiejuce'
➜ cookiecutter https://github.com/madskjeldgaard/Cookiejuce
You've downloaded /Users/Dataexcess/.cookiecutters/Cookiejuce before. Is it okay to delete and re-download it? [yes]: yes
Unable to load extension: No module named html.entities
What am I doing wrong?
Thnx

**Comment by dataexcess** [comment]
Yeah probably something with python! :

`/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '—version': [Errno 2] No such file or directory`

Urgh I hate python and its version issues

**Comment by madskjeldgaard** [comment]
Ah sorry, my email client messed up the command. It is: ```python --version``` with two dashes.

But anyway, it looks like you are running python2, and I don't think this is supported by cookiecutter. 

Try uninstalling the cookiecutter pip package again and install it for python3. 

On Mac you have have a `pip3` command which will make sure it install for python3.

```pip3 install cookiecutter``` 

and then run your cookiecutter command.

Also, just to verify, you can check the version of cookiecutter itself and post here if you run into issues.

```cookiecutter --version```

On my MacOS system this outputs:

```
Cookiecutter 2.5.0 from /opt/homebrew/lib/python3.11/site-packages (Python 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1
.0.2.5)])
```

**Comment by dataexcess** [comment]
Thank you it worked!

**Comment by madskjeldgaard** [comment]
I added a note to the readme about this now. Thanks for reporting.
