### ISSUE TITLE
Building seems to fail when project name features a hyphen

### ISSUE THREAD

**Issue by glocq** [madskjeldgaard/Cookiejuce#4]
Steps to reproduce:
1. Run `cookiecutter https://github.com/madskjeldgaard/Cookiejuce`. When prompted for project name, input a string that features a hyphen, such as `my-project`.
2. `cd my-project`, `mkdir build`, `cd build`
3. Run `cmake ..`, then `make`.

Build fails with:
```
error: unexpected token
 --> src/lib.rs:6:27
  |
6 | #[cxx::bridge(namespace = "my-projectrustlib")]
  |                           ^^^^^^^^^^^^^^^^^^^
```

I cannot 100% guarantee that the error is related to the hyphen, but among the couple projects I have tried so far, the only ones that fail are the hyphenated ones.

Maybe users are just not supposed to hyphen project names? If so, it would be helpful if project setup failed immediately with a helpful error message.

**Comment by madskjeldgaard** [comment]
Great find, thanks ! This should be easily fixable :-)Sent from my iPhoneOn 5 Mar 2024, at 13.56, Grégoire Locqueville ***@***.***> wrote:﻿
Steps to reproduce:

Run cookiecutter https://github.com/madskjeldgaard/Cookiejuce. When prompted for project name, input a string that features a hyphen, such as my-project.
cd my-project, mkdir build, cd build
Run cmake .., then make.

Build fails with:
error: unexpected token
 --> src/lib.rs:6:27
  |
6 | #[cxx::bridge(namespace = "my-projectrustlib")]
  |                           ^^^^^^^^^^^^^^^^^^^

I cannot 100% guarantee that the error is related to the hyphen, but among the couple projects I have tried so far, the only ones that fail are the hyphenated ones.
Maybe users are just not supposed to hyphen project names? If so, it would be helpful if project setup failed immediately with a helpful error message.

**Comment by madskjeldgaard** [comment]
Pushing a fix for this in a moment :)

**Comment by madskjeldgaard** [comment]
Try again latest version @glocq and reopen this if it does not work

**Comment by glocq** [comment]
Seems to work!
